// logs.js
Page({
  data: {
    skipUrl: 'https://union-click.jd.com/jdc?e=&p=JF8BANIJK1olXQUHV1teDUoeC18IGloUXQAFXVhZDUonRzBQRQQlBENHFRxWFlVPRjtUBABAQlRcCEBdCUoWA2kPEl0RWAcdDRsBVXtDeA9wUAFNIWZCIgkndgpDdDFeRD9lUQoyUV5cCUwUAWsJHmsWXAYEXVZYCUoQM18IHmtXM1tDFRUWQBBcRl8JK1sSWAYCXVtcC0MXBGw4G1MRbVVaH0IfUBRJM184GGslbQYyV24DZkpEBW0JGVkSM1xLHFkAURJBbW8KGVkcXwIGVm5fCUoVAV8',
  },
  onLoad() {
    
  }
})
